<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="DetalleVentas.aspx.cs" Inherits="PandaMay.Empleados.DetalleVentas" %>
<asp:Content ID="Content1" ContentPlaceHolderID="title" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="body" runat="server">
    <style>
.divizquierda{
width:35%;
height: 86%;
background-color:whitesmoke;
position: absolute;
left:0%;
}
.divderecha{
width:65%;
height: 86%;
position: absolute;
right:0%;
}
</style>
    <div id="div1" runat="server" style="width:100%; height:87%; ">
             <div class="divizquierda" style="border-color:black;background-repeat :no-repeat;  " >
                     <div class="container text-center" style=" background-color:transparent; width:100%; height: 90%; background-repeat :no-repeat;  z-index:initial;overflow-y:scroll" >
                         <p class="centrado">
                 <asp:GridView ID="GridView2" runat="server" ForeColor="Black" Width="100%" BorderColor="Transparent" CellSpacing="2" HorizontalAlign="Center" BackColor="Transparent" AutoPostBack="True"

                     AutoGenerateEditButton="true"
                        AutoGenerateColumns="false" 
                        AutoGenerateDeleteButton="true"
                        OnRowDeleting="Eliminar" TextOnRowDeletedEdit="Cancelar2"
                        OnRowCancelingEdit="RowCancelingEvent1" TextOnRowCanceledEdit="Cancelar2"
                        OnRowEditing="RowEditingEvent1" TextOnRowEdited="Modificar"
                        OnRowUpdating="RowUpdatingEvent1" TextOnRowUpdated="Actualizar2" >
                     <EditRowStyle BackColor="#fca669" Font-Bold="true" />
                         <HeaderStyle BackColor="Black" Font-Bold="True" Font-Italic="False" ForeColor="White"/>
                        <SelectedRowStyle BorderStyle="Solid" />

                            <Columns>
                        <asp:TemplateField HeaderText="Cantidad">
                        <ItemTemplate>
                        <asp:Label ID="Label9" runat="server" Text='<% # Bind("Cantidad") %>' Enabled="true" Width="60px" Height="65"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                        <asp:TextBox ID="TextBox9" runat="server" Text='<% # Bind("Cantidad") %>' Enabled="true" Width="50px" Height="65" TextMode="Number"></asp:TextBox>
                        </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Nombre">
                        <ItemTemplate>
                        <asp:Label ID="Label10" runat="server" Text='<% # Bind("Nombre") %>' Enabled="false" Width="210px" Height="65"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                        <asp:TextBox ID="TextBox10" runat="server" Text='<% # Bind("Nombre") %>' Enabled="false" Width="160px" Height="65" ></asp:TextBox>
                        </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Precio">
                        <ItemTemplate>
                        <asp:Label ID="Label11" runat="server" Text='<% # Bind("Precio") %>' Enabled="true" Width="60px" Height="65"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                        <asp:TextBox ID="TextBox11" runat="server" Text='<% # Bind("Precio") %>' Enabled="true" Width="50px" Height="65" TextMode="Number"></asp:TextBox>
                        </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Total">
                        <ItemTemplate>
                        <asp:Label ID="Label12" runat="server" Text='<% # Bind("Total") %>' Enabled="false" Width="60px" Height="65"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                        <asp:TextBox ID="TextBox12" runat="server" Text='<% # Bind("Total") %>' Enabled="false" Width="50px" Height="65"></asp:TextBox>
                        </EditItemTemplate>
                        </asp:TemplateField>

                        </Columns>
                        </asp:GridView>
                             <p />
                         </div>
                 <div class="container text-center" style=" background-color:transparent;  height: 5%; border-color:black; " >
     <asp:Label ID="Label2" runat="server" Font-Bold="true" Font-Size="X-Large" Enabled="false" Text="Total de esta venta: Q"></asp:Label>
     <asp:Label ID="Label1" runat="server" Font-Bold="true" Font-Size="X-Large" Enabled="false" Text="0"></asp:Label>
 </div>
                 <asp:GridView ID="GridView3" runat="server" Visible="false"> </asp:GridView>
 
         
             </div>
             <div class="divderecha" style=" background-color:white; border-color:black;background-repeat :no-repeat;  z-index: auto; " >
                <div class="container text-center" style=" background-color:lightgray; width:100%; height: 7%; border-color:black;background-repeat :no-repeat;  z-index: auto; " >
                <p class="centrado">
                    <asp:Button ID="Button3" CssClass="orangebutton" runat="server" Text="<-Anterior" OnClick="Anterior" />
                    <asp:Button ID="Button4" CssClass="orangebutton" runat="server" Text="Siguiente->" OnClick="Siguiente" />
                   
                   <%-- SqlDataSource que alimenta el DropDownList --%>
<asp:SqlDataSource
    ID="SqlDataSource4"
    runat="server"
    ConnectionString="<%$ ConnectionStrings:ConnectionString4 %>"
    SelectCommand="
      SELECT a.idtienda, a.nombre
      FROM tiendas a
      INNER JOIN empleadostiendas b ON a.idtienda = b.idtienda
      INNER JOIN empleados c      ON b.idempleado = c.idempleado
      INNER JOIN usuarios d       ON c.idusuario  = d.idusuario
      WHERE d.usuario = @nombre
      ORDER BY a.nombre ASC">
  <SelectParameters>
    <asp:SessionParameter
      Name="nombre"
      SessionField="usuario"
      Type="String" />
  </SelectParameters>
</asp:SqlDataSource>

<%-- DropDownList de tiendas --%>
<asp:DropDownList
    ID="DropDownList5"
    runat="server"
    DataSourceID="SqlDataSource4"
    DataTextField="nombre"
    DataValueField="idtienda"
    AutoPostBack="True"
    OnSelectedIndexChanged="ddltienda_SelectedIndexChanged">
    <%-- Ítem estático que aparece antes de los datos enlazados --%>
    <asp:ListItem Value="0" Text="--Tienda--" />
</asp:DropDownList>


                    <asp:TextBox ID="TextBox1" CssClass="buscador" runat="server" placeholder="Buscar Productos..." OnSelectedIndexChanged="TextBox1_SelectedIndexChanged" OnTextChanged="TextBox1_TextChanged" AutoPostBack="True" TextMode="Search"></asp:TextBox>
                  </p>
                </div> 
                 <div class="container text-center" style=" background-color:white; width:100%; height: 88%; background-repeat :no-repeat;  z-index: auto; overflow-y:scroll" >
                    <asp:GridView 
    ID="GridView1" 
    runat="server"
    DataKeyNames="idproducto,idimagen"
    AutoGenerateColumns="false"
    AutoGenerateSelectButton="True"
    OnSelectedIndexChanging="Select1"
    OnRowDataBound="GridView1_RowDataBound"
    CssClass="tabla-precios"
    GridLines="Both"
    BorderColor="#ccc"
    BorderWidth="1px"
    CellSpacing="5"
    HorizontalAlign="Center"
    Width="100%">
  
  <HeaderStyle BackColor="Black" ForeColor="White" Font-Bold="True" />
  <SelectedRowStyle BackColor="#80cdbb" Font-Bold="True" />

  <Columns>
    <%-- Nombre --%>
    <asp:TemplateField HeaderText="Producto">
      <ItemTemplate>
        <asp:Label ID="lblNombreProd" runat="server"
           Text='<%# Eval("nombre") %>' />
      </ItemTemplate>
    </asp:TemplateField>

    <asp:TemplateField HeaderText="Precio (U)">
  <ItemTemplate>
    <asp:Label 
       ID="lblPrecioU" 
       runat="server"
       Text='<%# Eval("unidad",   "{0:C}") %>' />
  </ItemTemplate>
</asp:TemplateField>

<asp:TemplateField HeaderText="Precio (3)">
  <ItemTemplate>
    <asp:Label 
       ID="lblPrecio3" 
       runat="server"
       Text='<%# Eval("tresomas","{0:C}") %>' />
  </ItemTemplate>
</asp:TemplateField>

<asp:TemplateField HeaderText="Precio (Doc)">
  <ItemTemplate>
    <asp:Label 
       ID="lblDocena" 
       runat="server"
       Text='<%# Eval("docena",  "{0:C}") %>' />
  </ItemTemplate>
</asp:TemplateField>

<asp:TemplateField HeaderText="Precio (F)">
  <ItemTemplate>
    <asp:Label 
       ID="lblFardo" 
       runat="server"
       Text='<%# Eval("fardo",   "{0:C}") %>' />
  </ItemTemplate>
</asp:TemplateField>


    <%-- Código de barras --%>
    <asp:TemplateField HeaderText="Cód. Barras">
      <ItemTemplate>
        <asp:Label ID="lblCB" runat="server"
           Text='<%# Eval("codigodebarras") %>' />
      </ItemTemplate>
    </asp:TemplateField>

    <%-- Referencia --%>
    <asp:TemplateField HeaderText="Referencia">
      <ItemTemplate>
        <asp:Label ID="lblRef" runat="server"
           Text='<%# Eval("referencia") %>' />
      </ItemTemplate>
    </asp:TemplateField>

    <%-- Imagen escondida --%>
    <asp:BoundField DataField="idimagen" Visible="false" />

    <%-- Miniatura --%>
    <asp:TemplateField HeaderText="Imagen">
      <ItemTemplate>
        <asp:Image ID="imgMini" runat="server" Width="60" Height="60" />
      </ItemTemplate>
    </asp:TemplateField>
  </Columns>
</asp:GridView>
                </div> 
          </div>
        </div>
    <div id="div2" Visible="false" runat="server" style="width:100%; height:84%; ">
    <div class="container text-center" style="   width:75%;   border-color:black;background-repeat :no-repeat;  position:initial; z-index: auto;" >
  <p class="centrado">
      <asp:Button ID="Button1" CssClass="orangebutton" OnClick="anterior2" runat="server" Text="<-Anterior" />
      <asp:Button ID="Button2" CssClass="greenbutton" OnClick="guardar" runat="server" Text="Guadar ✓" />
      <asp:Button ID="Button5" CssClass="redbutton" runat="server" Text="Cancelar" Enabled="false" Visible="False" />
      </p>
                  </div>
<div class="container text-center" style="   width:90%;   background-color:#ffd2cc;" >
    <p class="centrado">
         
    <asp:Label ID="Label4" runat="server" Text="Datos del Cliente" Font-Bold="True" Font-Size="X-Large" ForeColor=Black></asp:Label>
    <br />
          <br />
  <asp:TextBox ID="txtnombre" CssClass="textbox" runat="server" placeholder="Nombre" ></asp:TextBox>
        
        <asp:DropDownList ID="ddldepartamento" CssClass="dropdownlist" runat="server" OnSelectedIndexChanged="ddldepartamento_SelectedIndexChanged" AutoPostBack="True"  AppendDataBoundItems="True" DataSourceID="SqlDataSource3" DataTextField="nombre" DataValueField="iddepartamento" >
                <asp:ListItem Selected="True" Value="0">--Departamento</asp:ListItem>
                </asp:DropDownList>
                <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString4 %>" SelectCommand="select* from departamentos;"></asp:SqlDataSource>
    
             <asp:Label ID="Departamento0" runat="server"></asp:Label>
              
        <asp:DropDownList ID="ddlmunicipio" CssClass="dropdownlist" runat="server" OnSelectedIndexChanged="ddlmunicipio_SelectedIndexChanged" AutoPostBack="True"  AppendDataBoundItems="True" DataSourceID="SqlDataSource5" DataTextField="nombre" DataValueField="idmunicipio" >
                    <asp:ListItem Selected="True" Value="0">--Municipio</asp:ListItem>
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource5" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString4 %>" SelectCommand="SELECT [idmunicipio], [nombre] FROM [municipios] WHERE ([iddepartamento] = @iddepartamento)">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="ddldepartamento" Name="iddepartamento" PropertyName="SelectedValue" Type="Int32" />
                        </SelectParameters>
                    </asp:SqlDataSource>
             <asp:Label ID="Municipio0" runat="server"></asp:Label>
         
        <asp:DropDownList ID="ddlzona" CssClass="dropdownlist" runat="server" OnSelectedIndexChanged="ddlzona_SelectedIndexChanged"  AppendDataBoundItems="True" DataSourceID="SqlDataSource6" DataTextField="nombre" DataValueField="idzona" AutoPostBack="True">
                    <asp:ListItem Selected="True" Value="0">--Zona, Aldea, Lugar</asp:ListItem>
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="SqlDataSource6" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString4 %>" SelectCommand="SELECT [idzona], [nombre] FROM [zonas] WHERE ([idmunicipio] = @idmunicipio)">
                            <SelectParameters>
                                <asp:ControlParameter ControlID="ddlmunicipio" Name="idmunicipio" PropertyName="SelectedValue" Type="Int32" />
                            </SelectParameters>
                        </asp:SqlDataSource>
<asp:Label ID="Zona0" runat="server"></asp:Label>
            
                    <asp:DropDownList ID="ddlzona0" runat="server" AppendDataBoundItems="True" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="idtarifa" DataValueField="idzona" OnSelectedIndexChanged="ddlzona0_SelectedIndexChanged" BackColor="GhostWhite" Font-Overline="False" Font-Size="Smaller" Font-Strikeout="False" Font-Underline="False" ForeColor="GhostWhite" Visible="false">
                            <asp:ListItem></asp:ListItem>
                        </asp:DropDownList>
            
             <asp:Label ID="tarifaenvio" runat="server" Text="Tarifa de Envio:  Q" Visible="False"></asp:Label>
                        &nbsp;<asp:Label ID="montoenvio" runat="server"></asp:Label>
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString4 %>" SelectCommand="SELECT * FROM [zonas] WHERE ([idzona] = @idzona)">
                            <SelectParameters>
                                <asp:ControlParameter ControlID="ddlzona" Name="idzona" PropertyName="SelectedValue" Type="Int32" />
                            </SelectParameters>
                        </asp:SqlDataSource>
         
        <asp:TextBox ID="TextBox2" CssClass="textbox" runat="server" placeholder="Dirección" ></asp:TextBox>
        
        <asp:TextBox ID="TextBox3" CssClass="textbox" runat="server" placeholder="Teléfonos" ></asp:TextBox>
        <br /><br />
        <asp:TextBox ID="TextBox31" CssClass="textbox" runat="server" placeholder="Usuario" ></asp:TextBox>
         
        <asp:TextBox ID="TextBox6" CssClass="textbox" runat="server" placeholder="Cambios" ></asp:TextBox>
        
        <asp:TextBox ID="TextBox7" CssClass="textbox" runat="server" placeholder="Observaciones" ></asp:TextBox>

        <asp:TextBox ID="TextBox32" CssClass="textbox" runat="server" placeholder="Codigo de cliente" TextMode="Number" ></asp:TextBox>

        <br /><br />

         </p></div>

            <div class="container text-center" style="   width:90%;   background-color:#ffd2cc;" >
      <p class="centrado">
       <br />
       
  <asp:Label ID="Label5" runat="server" Text="Datos de la Venta" Font-Bold="True" Font-Size="X-Large" ForeColor=Black></asp:Label>
   <br />  <br />
          <asp:TextBox ID="TextBox14" CssClass="textbox" runat="server" placeholder="No. Orden" Enabled="False"></asp:TextBox>

              <asp:TextBox ID="TextBox36" CssClass="textbox"  runat="server"  Enabled="False"></asp:TextBox>

                  <asp:DropDownList ID="DropDownList1" CssClass="dropdownlist" Enabled="false" runat="server" OnSelectedIndexChanged="ddltienda_SelectedIndexChanged" AutoPostBack="True" AppendDataBoundItems="True" DataSourceID="SqlDataSource4" DataTextField="nombre" DataValueField="idtienda">
     </asp:DropDownList>
<asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString4 %>" SelectCommand="select * from tiendas a left join empleadostiendas b on a.idtienda=b.idtienda left join empleados c on b.idempleado=c.idempleado left join usuarios d on c.idusuario=d.idusuario where d.usuario= @nombre order by a.nombre asc;">
  <SelectParameters>
  <asp:SessionParameter SessionField="usuario" Name="nombre" Type="String"></asp:SessionParameter>
  </SelectParameters>
  </asp:SqlDataSource>
        <br /><br />
        </p></div>

     <div id="div3" class="container text-center"  runat="server" style="width:90%; background-color:#ffd2cc;  ">
       <br />
       
  <asp:Label ID="Label6" runat="server" Text="Datos del Pago" Font-Bold="True" Font-Size="X-Large" ForeColor=Black></asp:Label>
   <br /> 
            <div class="container text-center" style=" width:30%;   background-color:#80cdbb;" >
                <br />
  <asp:Label ID="Label7" runat="server" Font-Bold="true" Font-Size="Large" ForeColor="White" Enabled="false" Text="Total de esta venta: Q"></asp:Label>
   <asp:Label ID="Label8" runat="server" Font-Bold="true" Font-Size="Large" ForeColor="White" Enabled="false" Text="0"></asp:Label>
            <br /><br />
          <asp:Label ID="Label3" runat="server" Font-Bold="true" Font-Size="Large" ForeColor="White" Enabled="false" Text="Diferencia: Q"></asp:Label>
 <asp:Label ID="Label10" runat="server" Font-Bold="true" Font-Size="Large" ForeColor="White" Enabled="false"></asp:Label>

<br />
                <asp:Label ID="Label17" ForeColor="Red" runat="server" Text="Label"></asp:Label>
                <br /></div><br />
           
   <asp:TextBox ID="TextBox37" CssClass="textbox" AutoPostBack="true" runat="server" placeholder="Efectivo" TextMode="Number" ></asp:TextBox>

<br /> <br />

                             <asp:DropDownList ID="DropDownList2" CssClass="dropdownlist" runat="server"   AutoPostBack="True" AppendDataBoundItems="True" OnSelectedIndexChanged="ddlbanco_SelectedIndexChanged" DataSourceID="SqlDataSource7" DataTextField="nombrebanco" DataValueField="idbanco">
                            <asp:ListItem Selected="True" Value="0">--Banco</asp:ListItem>
                             </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSource7" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString4 %>" SelectCommand="select*from bancos where idusuario=4;">  </asp:SqlDataSource>
           <asp:TextBox ID="TextBox38" CssClass="textbox" TextMode="Number" AutoPostBack="true" placeholder="Numero de cuenta" Enabled="false" runat="server" ></asp:TextBox>
       
          <asp:TextBox ID="TextBox8" CssClass="textbox" TextMode="Number" AutoPostBack="true" placeholder="Monto Transferencia 1" runat="server" ></asp:TextBox>
        
             <asp:TextBox ID="TextBox17" CssClass="textbox" runat="server" placeholder="Referencia" TextMode="Number" ></asp:TextBox>
        
             <asp:TextBox ID="TextBox9" CssClass="textbox" runat="server" placeholder="Fecha" TextMode="Date" ></asp:TextBox>

             <asp:TextBox ID="TextBox25" CssClass="textbox" runat="server" placeholder="Pendiente por validar" Enabled="false"></asp:TextBox>

        <br /> <br />
                             <asp:DropDownList ID="DropDownList3" CssClass="dropdownlist" runat="server"   AutoPostBack="True" AppendDataBoundItems="True" OnSelectedIndexChanged="ddlbanco2_SelectedIndexChanged" DataSourceID="SqlDataSource8" DataTextField="nombrebanco" DataValueField="idbanco">
                 <asp:ListItem Selected="True" Value="0">--Banco</asp:ListItem>
                  </asp:DropDownList>
                 <asp:SqlDataSource ID="SqlDataSource8" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString4 %>" SelectCommand="select*from bancos where idusuario=4;">  </asp:SqlDataSource>
<asp:TextBox ID="TextBox39" CssClass="textbox" TextMode="Number" AutoPostBack="true" placeholder="Numero de cuenta" Enabled="false" runat="server" ></asp:TextBox>
       
      
          <asp:TextBox ID="TextBox10" CssClass="textbox"  TextMode="Number" runat="server" AutoPostBack="true" placeholder="Monto Transferencia 2" ></asp:TextBox>
       
             <asp:TextBox ID="TextBox11" CssClass="textbox" runat="server" placeholder="Referencia" TextMode="Number" ></asp:TextBox>
        
             <asp:TextBox ID="TextBox12" CssClass="textbox" runat="server" placeholder="Fecha" TextMode="Date" ></asp:TextBox>

               <asp:TextBox ID="TextBox24" CssClass="textbox" runat="server" placeholder="Pendiente por validar" Enabled="false"></asp:TextBox>
        <br /><br />
        </div>
                   
        </div>
</asp:Content>
